### ISSUE TITLE
Cross-compiling for Raspberry Pi Zero with Docker fails

### ISSUE THREAD

**Issue by JohnDoneth** [alexcrichton/backtrace-rs#106]
## Description

My project no longer compiles now that multiple crates my project depends on have updated. Those crates now depend on **error-chain**, and **failure** which depend on **backtrace-rs** which depends on **backtrace-sys** which is not compiling. 😢 

I've been trying to work around this issue for weeks now, and have given up, and am looking for some help. I chose Docker for this issue as it's the easiest to demonstrate and reproduce.

Edit: I have updated all libraries to latest and now I am getting a different error with gcc and the option "-m64" which indicates to me that the architecture of the target is not being recognized?

---
## Details

- **Host** x86_64-unknown-linux-gnu
- **Target** arm-unknown-linux-gnueabihf
- **Library Version:** backtrace-sys v0.1.22
---
## Steps to reproduce:

1. Create a project which depends upon **backtrace-sys** directly or indirectly.

2. Execute this [docker image](https://github.com/dlecan/rust-crosscompiler-arm) with the following command:
```
docker run -it --rm \
  -v $(pwd):/source \
  -e RUST_BACKTRACE=1 \
  dlecan/rust-crosscompiler-arm:stable
```

---
## Output:
```
$ sh dbuild.sh
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading serde_json v1.0.18
 Downloading chrono v0.4.2
 Downloading serde_derive v1.0.63
 Downloading serde v1.0.63
 Downloading actix-web v0.6.10
 Downloading dtoa v0.4.2
 Downloading itoa v0.4.1
 Downloading num-integer v0.1.38
 Downloading time v0.1.40
 Downloading num-traits v0.2.4
 Downloading libc v0.2.41
 Downloading proc-macro2 v0.4.4
 Downloading syn v0.14.1
 Downloading quote v0.6.3
 Downloading unicode-xid v0.1.0
 Downloading net2 v0.2.32
 Downloading rand v0.4.2
 Downloading cookie v0.10.1
 Downloading log v0.4.1
 Downloading language-tags v0.2.2
 Downloading smallvec v0.6.1
 Downloading futures-cpupool v0.1.8
 Downloading flate2 v1.0.1
 Downloading mime_guess v2.0.0-alpha.4
 Downloading bytes v0.4.8
 Downloading actix v0.5.7
 Downloading http-range v0.1.1
 Downloading serde_urlencoded v0.5.2
 Downloading bitflags v1.0.3
 Downloading base64 v0.9.1
 Downloading mio v0.6.14
 Downloading percent-encoding v1.0.1
 Downloading tokio-core v0.1.17
 Downloading sha1 v0.6.0
 Downloading mime v0.3.7
 Downloading byteorder v1.2.3
 Downloading brotli2 v0.3.2
 Downloading futures v0.1.21
 Downloading url v1.7.0
 Downloading encoding v0.2.33
 Downloading http v0.1.5
 Downloading h2 v0.1.8
 Downloading tokio-io v0.1.6
 Downloading httparse v1.2.4
 Downloading failure v0.1.1
 Downloading slab v0.4.0
 Downloading regex v1.0.0
 Downloading lazy_static v1.0.1
 Downloading num_cpus v1.8.0
 Downloading cfg-if v0.1.3
 Downloading ring v0.12.1
 Downloading base64 v0.6.0
 Downloading untrusted v0.5.1
 Downloading lazy_static v0.2.11
 Downloading gcc v0.3.54
 Downloading rayon v0.8.2
 Downloading rayon-core v1.4.0
 Downloading crossbeam-deque v0.2.0
 Downloading crossbeam-utils v0.2.2
 Downloading crossbeam-epoch v0.3.1
 Downloading scopeguard v0.3.3
 Downloading nodrop v0.1.12
 Downloading arrayvec v0.4.7
 Downloading memoffset v0.2.1
 Downloading idna v0.1.4
 Downloading matches v0.1.6
 Downloading unicode-normalization v0.1.7
 Downloading unicode-bidi v0.3.4
 Downloading encoding-index-japanese v1.20141219.5
 Downloading encoding-index-singlebyte v1.20141219.5
 Downloading encoding-index-korean v1.20141219.5
 Downloading encoding-index-tradchinese v1.20141219.5
 Downloading encoding-index-simpchinese v1.20141219.5
 Downloading encoding_index_tests v0.1.4
 Downloading safemem v0.2.0
 Downloading miniz-sys v0.1.10
 Downloading cc v1.0.15
 Downloading unicase v1.4.2
 Downloading phf v0.7.22
 Downloading version_check v0.1.3
 Downloading phf_shared v0.7.22
 Downloading siphasher v0.2.2
 Downloading unicase v2.1.0
 Downloading phf_codegen v0.7.22
 Downloading phf_generator v0.7.22
 Downloading iovec v0.1.2
 Downloading trust-dns-resolver v0.8.2
 Downloading crossbeam-channel v0.1.3
 Downloading uuid v0.6.5
 Downloading actix_derive v0.2.0
 Downloading tokio-signal v0.1.5
 Downloading resolv-conf v0.6.1
 Downloading error-chain v0.1.12
 Downloading trust-dns-proto v0.3.3
 Downloading lru-cache v0.1.1
 Downloading scoped-tls v0.1.2
 Downloading tokio-executor v0.1.2
 Downloading tokio v0.1.6
 Downloading tokio-reactor v0.1.1
 Downloading tokio-timer v0.2.3
 Downloading tokio-udp v0.1.0
 Downloading tokio-tcp v0.1.0
 Downloading tokio-threadpool v0.1.3
 Downloading tokio-fs v0.1.0
 Downloading lazycell v0.6.0
 Downloading crossbeam-deque v0.3.1
 Downloading crossbeam-epoch v0.4.1
 Downloading crossbeam-utils v0.3.2
 Downloading hostname v0.1.5
 Downloading quick-error v1.2.2
 Downloading backtrace v0.2.3
 Downloading kernel32-sys v0.2.2
 Downloading rustc-demangle v0.1.8
 Downloading winapi v0.2.8
 Downloading backtrace-sys v0.1.22
 Downloading dbghelp-sys v0.2.0
 Downloading winapi-build v0.1.1
 Downloading pkg-config v0.3.11
 Downloading linked-hash-map v0.4.2
 Downloading parking_lot v0.5.5
 Downloading owning_ref v0.3.3
 Downloading parking_lot_core v0.2.14
 Downloading stable_deref_trait v1.0.0
 Downloading quote v0.3.15
 Downloading syn v0.11.11
 Downloading rand v0.3.22
 Downloading unicode-xid v0.0.4
 Downloading synom v0.11.3
 Downloading mio-uds v0.6.6
 Downloading failure_derive v0.1.1
 Downloading backtrace v0.3.8
 Downloading synstructure v0.6.1
 Downloading skeptic v0.13.3
 Downloading walkdir v2.1.4
 Downloading cargo_metadata v0.5.4
 Downloading tempdir v0.3.7
 Downloading glob v0.2.11
 Downloading error-chain v0.11.0
 Downloading pulldown-cmark v0.1.2
 Downloading bytecount v0.3.1
 Downloading same-file v1.0.2
 Downloading semver v0.9.0
 Downloading semver-parser v0.7.0
 Downloading remove_dir_all v0.5.1
 Downloading bitflags v0.9.1
 Downloading brotli-sys v0.3.2
 Downloading fnv v1.0.6
 Downloading string v0.1.0
 Downloading indexmap v1.0.1
 Downloading utf8-ranges v1.0.0
 Downloading regex-syntax v0.6.0
 Downloading memchr v2.0.1
 Downloading thread_local v0.3.5
 Downloading aho-corasick v0.6.4
 Downloading ucd-util v0.1.1
 Downloading unreachable v1.0.0
 Downloading void v1.0.2
   Compiling libc v0.2.41
   Compiling pkg-config v0.3.11
   Compiling lazy_static v1.0.1
   Compiling serde v1.0.63
   Compiling quick-error v1.2.2
   Compiling iovec v0.1.2
   Compiling net2 v0.2.32
   Compiling rand v0.4.2
   Compiling num_cpus v1.8.0
   Compiling hostname v0.1.5
   Compiling memchr v2.0.1
   Compiling time v0.1.40
   Compiling actix-web v0.6.10
   Compiling proc-macro2 v0.4.4
   Compiling backtrace-sys v0.1.22
   Compiling rayon-core v1.4.0
   Compiling crossbeam-epoch v0.4.1
   Compiling bytes v0.4.8
   Compiling mio v0.6.14
   Compiling parking_lot_core v0.2.14
   Compiling uuid v0.6.5
   Compiling resolv-conf v0.6.1
   Compiling futures-cpupool v0.1.8
   Compiling aho-corasick v0.6.4
   Compiling crossbeam-epoch v0.3.1
   Compiling kernel32-sys v0.2.2
   Compiling dbghelp-sys v0.2.0
error: failed to run custom build command for `backtrace-sys v0.1.22`
process didn't exit successfully: `/source/target/release/build/backtrace-sys-aacf5e176a36acbf/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-gnu = None
CC_x86_64_unknown_linux_gnu = None
HOST_CC = None
CC = Some("arm-linux-gnueabihf-gcc-with-link-search")
TARGET = Some("x86_64-unknown-linux-gnu")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-gnu = None
CFLAGS_x86_64_unknown_linux_gnu = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("false")
running: "arm-linux-gnueabihf-gcc-with-link-search" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "src/libbacktrace" "-I" "/source/target/release/build/backtrace-sys-1f1bf399bf6d8bd4/out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=64" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/source/target/release/build/backtrace-sys-1f1bf399bf6d8bd4/out/src/libbacktrace/alloc.o" "-c" "src/libbacktrace/alloc.c"
cargo:warning=arm-linux-gnueabihf-gcc: error: unrecognized command line option '-m64'
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "arm-linux-gnueabihf-gcc-with-link-search" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "src/libbacktrace" "-I" "/source/target/release/build/backtrace-sys-1f1bf399bf6d8bd4/out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=64" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/source/target/release/build/backtrace-sys-1f1bf399bf6d8bd4/out/src/libbacktrace/alloc.o" "-c" "src/libbacktrace/alloc.c" with args "arm-linux-gnueabihf-gcc-with-link-search" did not execute successfully (status code exit code: 1).

', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.15/src/lib.rs:2158:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:349
   6: cc::fail
   7: cc::Build::compile
   8: build_script_build::main
   9: std::rt::lang_start::{{closure}}
  10: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  12: std::rt::lang_start_internal
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  13: main
  14: __libc_start_main
  15: <unknown>

warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by JohnDoneth** [comment]
That was it! I cant thank you enough. Passing `gcc` to `$CC` got it working.

I was correctly passing `$CC_arm_unknown_linux_gnu` but I didn't realize that the host $CC was incorrect.

**Correct Docker Args:**
-e CC=gcc
-e CC_arm_unknown_linux_gnu=arm-linux-gnueabihf-gcc-with-link-search
