### ISSUE TITLE
backtrace-sys v0.1.22 fails to compile with musl-gcc

### ISSUE THREAD

**Issue by sanmai-NL** [alexcrichton/backtrace-rs#107]
```
error: failed to run custom build command for `backtrace-sys v0.1.22`
process didn't exit successfully: `/home/sanmai/devel/Rust/target/release/build/backtrace-sys-dc11e967f9fd3e98/build-script-build` (exit code: 101)
--- stdout
cargo:rustc-link-search=native=/usr/lib
cargo:rustc-link-lib=unwind
TARGET = Some("x86_64-unknown-linux-musl")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-musl")
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-musl = None
CC_x86_64_unknown_linux_musl = None
TARGET_CC = None
CC = Some("musl-clang")
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-musl = None
CFLAGS_x86_64_unknown_linux_musl = None
TARGET_CFLAGS = None
CFLAGS = Some("-static -static-libgcc -fstack-protector-strong -fPIC -fno-plt -O2")
DEBUG = Some("false")
running: "musl-clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-static" "-static-libgcc" "-fstack-protector-strong" "-fPIC" "-fno-plt" "-O2" "--target=x86_64-unknown-linux-musl" "-I" "src/libbacktrace" "-I" "/home/sanmai/devel/Rust/target/x86_64-unknown-linux-musl/release/build/backtrace-sys-57e1c5f871b0c03c/out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=64" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/home/sanmai/devel/Rust/target/x86_64-unknown-linux-musl/release/build/backtrace-sys-57e1c5f871b0c03c/out/src/libbacktrace/alloc.o" "-c" "src/libbacktrace/alloc.c"
cargo:warning=clang-6.0: warning: argument unused during compilation: '-fuse-ld=musl-clang' [-Wunused-command-line-argument]
cargo:warning=clang-6.0: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
cargo:warning=clang-6.0: warning: argument unused during compilation: '-L-user-start' [-Wunused-command-line-argument]
cargo:warning=clang-6.0: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
cargo:warning=clang-6.0: warning: argument unused during compilation: '-L/usr/lib/musl/lib' [-Wunused-command-line-argument]
cargo:warning=clang-6.0: warning: argument unused during compilation: '-L-user-end' [-Wunused-command-line-argument]
exit code: 0
TARGET = Some("x86_64-unknown-linux-musl")
OPT_LEVEL = Some("3")
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
TARGET = Some("x86_64-unknown-linux-musl")
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
CC_x86_64-unknown-linux-musl = None
CC_x86_64_unknown_linux_musl = None
TARGET_CC = None
CC = Some("musl-clang")
TARGET = Some("x86_64-unknown-linux-musl")
HOST = Some("x86_64-unknown-linux-gnu")
CFLAGS_x86_64-unknown-linux-musl = None
CFLAGS_x86_64_unknown_linux_musl = None
TARGET_CFLAGS = None
CFLAGS = Some("-static -static-libgcc -fstack-protector-strong -fPIC -fno-plt -O2")
DEBUG = Some("false")
running: "musl-clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-static" "-static-libgcc" "-fstack-protector-strong" "-fPIC" "-fno-plt" "-O2" "--target=x86_64-unknown-linux-musl" "-I" "src/libbacktrace" "-I" "/home/sanmai/devel/Rust/target/x86_64-unknown-linux-musl/release/build/backtrace-sys-57e1c5f871b0c03c/out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=64" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/home/sanmai/devel/Rust/target/x86_64-unknown-linux-musl/release/build/backtrace-sys-57e1c5f871b0c03c/out/src/libbacktrace/backtrace.o" "-c" "src/libbacktrace/backtrace.c"
cargo:warning=clang-6.0: warning: argument unused during compilation: '-fuse-ld=musl-clang' [-Wunused-command-line-argument]
cargo:warning=clang-6.0: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
cargo:warning=clang-6.0: warning: argument unused during compilation: '-L-user-start' [-Wunused-command-line-argument]
cargo:warning=clang-6.0: warning: argument unused during compilation: '-static-libgcc' [-Wunused-command-line-argument]
cargo:warning=clang-6.0: warning: argument unused during compilation: '-L/usr/lib/musl/lib' [-Wunused-command-line-argument]
cargo:warning=clang-6.0: warning: argument unused during compilation: '-L-user-end' [-Wunused-command-line-argument]
cargo:warning=src/libbacktrace/backtrace.c:37:10: fatal error: 'unwind.h' file not found
cargo:warning=#include "unwind.h"
cargo:warning=         ^~~~~~~~~~
cargo:warning=1 error generated.
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "musl-clang" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-static" "-static-libgcc" "-fstack-protector-strong" "-fPIC" "-fno-plt" "-O2" "--target=x86_64-unknown-linux-musl" "-I" "src/libbacktrace" "-I" "/home/sanmai/devel/Rust/target/x86_64-unknown-linux-musl/release/build/backtrace-sys-57e1c5f871b0c03c/out" "-fvisibility=hidden" "-DBACKTRACE_ELF_SIZE=64" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/home/sanmai/devel/Rust/target/x86_64-unknown-linux-musl/release/build/backtrace-sys-57e1c5f871b0c03c/out/src/libbacktrace/backtrace.o" "-c" "src/libbacktrace/backtrace.c" with args "musl-clang" did not execute successfully (status code exit code: 1).

', /home/sanmai/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.17/src/lib.rs:2180:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:463
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:350
   6: cc::fail
   7: cc::Build::compile
   8: build_script_build::main
   9: std::rt::lang_start::{{closure}}
  10: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
  12: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:374
             at libstd/rt.rs:58
  13: main
  14: __libc_start_main
  15: _start

warning: build failed, waiting for other jobs to finish...
error: build failed
2018-05-29T18:07:38Z   ERROR    cargo build failed
thread 'main' panicked at 'explicit panic', builder/src/dpc.rs:189:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

## Meta
```
  rustc -V
rustc 1.28.0-nightly (5bf68db6e 2018-05-28)
```

**Comment by Ereski** [comment]
Fails with musl-clang as well since 0.1.20. v0.1.19 compiles.
