### ISSUE TITLE
Unable to compile due to malformed object (ar crs)

### ISSUE THREAD

**Issue by zandeck** [alexcrichton/backtrace-rs#128]
Hello,

When I try to compile the crate (0.1.24), I get the following error:
```

AR_x86_64-apple-darwin = None
AR_x86_64_apple_darwin = None
HOST_AR = None
AR = None
running: "ar" "crs" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/libbacktrace.a" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/alloc.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/dwarf.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/fileline.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/posix.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/read.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/sort.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/state.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/macho.o"
cargo:warning=/usr/local/Cellar/cctools/855/bin/ranlib: object: /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/libbacktrace.a(alloc.o) malformed object (unknown load command 1)
cargo:warning=ar: internal ranlib command failed
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "ar" "crs" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/libbacktrace.a" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/alloc.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/dwarf.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/fileline.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/posix.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/read.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/sort.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/state.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/macho.o" with args "ar" did not execute successfully (status code exit code: 1).

', /Users/matthieu/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:2260:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::try::do_call
             at libstd/panicking.rs:345
   7: cc::fail
             at /Users/matthieu/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:2260
   8: cc::Build::try_compile::{{closure}}
             at /Users/matthieu/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:933
   9: build_script_build::main
             at ./build.rs:93
  10: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
  13: <std::sync::mutex::Mutex<T>>::new
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  15: build_script_build::main
```

I am on macOS Mojave, and I tried installing twice Xcode and the Command Line Tools but it doesn't seem to help.

Do you have any idea of what might be missing?

Thank you,
Zandeck

**Comment by alexcrichton** [comment]
Curious! I'm unfortunately not sure what the cause of this is. Can you gist the full error log though? Maybe that has clues?

**Comment by zandeck** [comment]
I have been struggling for several day on this and I'm pretty sure something is missing, but impossible to find out what :/

You mean this?

```
192:hello matthieu$ RUST_BACKTRACE=1 cargo build
   Compiling backtrace-sys v0.1.24                                              
error: failed to run custom build command for `backtrace-sys v0.1.24`
process didn't exit successfully: `/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-93063ceea8be2996/build-script-build` (exit code: 101)
--- stdout
TARGET = Some("x86_64-apple-darwin")
OPT_LEVEL = Some("0")
HOST = Some("x86_64-apple-darwin")
CC_x86_64-apple-darwin = None
CC_x86_64_apple_darwin = None
HOST_CC = None
CC = None
CFLAGS_x86_64-apple-darwin = None
CFLAGS_x86_64_apple_darwin = None
HOST_CFLAGS = None
CFLAGS = None
DEBUG = Some("true")
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/libbacktrace" "-I" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/alloc.o" "-c" "src/libbacktrace/alloc.c"
exit code: 0
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/libbacktrace" "-I" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/dwarf.o" "-c" "src/libbacktrace/dwarf.c"
exit code: 0
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/libbacktrace" "-I" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/fileline.o" "-c" "src/libbacktrace/fileline.c"
exit code: 0
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/libbacktrace" "-I" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/posix.o" "-c" "src/libbacktrace/posix.c"
exit code: 0
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/libbacktrace" "-I" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/read.o" "-c" "src/libbacktrace/read.c"
exit code: 0
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/libbacktrace" "-I" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/sort.o" "-c" "src/libbacktrace/sort.c"
exit code: 0
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/libbacktrace" "-I" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/state.o" "-c" "src/libbacktrace/state.c"
exit code: 0
running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-I" "src/libbacktrace" "-I" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out" "-DBACKTRACE_SUPPORTED=1" "-DBACKTRACE_USES_MALLOC=1" "-DBACKTRACE_SUPPORTS_THREADS=0" "-DBACKTRACE_SUPPORTS_DATA=0" "-DHAVE_DL_ITERATE_PHDR=1" "-D_GNU_SOURCE=1" "-D_LARGE_FILES=1" "-Dbacktrace_full=__rbt_backtrace_full" "-Dbacktrace_dwarf_add=__rbt_backtrace_dwarf_add" "-Dbacktrace_initialize=__rbt_backtrace_initialize" "-Dbacktrace_pcinfo=__rbt_backtrace_pcinfo" "-Dbacktrace_syminfo=__rbt_backtrace_syminfo" "-Dbacktrace_get_view=__rbt_backtrace_get_view" "-Dbacktrace_release_view=__rbt_backtrace_release_view" "-Dbacktrace_alloc=__rbt_backtrace_alloc" "-Dbacktrace_free=__rbt_backtrace_free" "-Dbacktrace_vector_finish=__rbt_backtrace_vector_finish" "-Dbacktrace_vector_grow=__rbt_backtrace_vector_grow" "-Dbacktrace_vector_release=__rbt_backtrace_vector_release" "-Dbacktrace_close=__rbt_backtrace_close" "-Dbacktrace_open=__rbt_backtrace_open" "-Dbacktrace_print=__rbt_backtrace_print" "-Dbacktrace_simple=__rbt_backtrace_simple" "-Dbacktrace_qsort=__rbt_backtrace_qsort" "-Dbacktrace_create_state=__rbt_backtrace_create_state" "-Dbacktrace_uncompress_zdebug=__rbt_backtrace_uncompress_zdebug" "-o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/macho.o" "-c" "src/libbacktrace/macho.c"
exit code: 0
AR_x86_64-apple-darwin = None
AR_x86_64_apple_darwin = None
HOST_AR = None
AR = None
running: "ar" "crs" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/libbacktrace.a" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/alloc.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/dwarf.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/fileline.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/posix.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/read.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/sort.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/state.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/macho.o"
cargo:warning=/usr/local/Cellar/cctools/855/bin/ranlib: object: /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/libbacktrace.a(alloc.o) malformed object (unknown load command 1)
cargo:warning=ar: internal ranlib command failed
exit code: 1

--- stderr
thread 'main' panicked at '

Internal error occurred: Command "ar" "crs" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/libbacktrace.a" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/alloc.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/dwarf.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/fileline.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/posix.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/read.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/sort.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/state.o" "/Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-3f8ca4cfbc1b1806/out/src/libbacktrace/macho.o" with args "ar" did not execute successfully (status code exit code: 1).

', /Users/matthieu/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:2260:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::try::do_call
             at libstd/panicking.rs:345
   7: cc::fail
             at /Users/matthieu/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:2260
   8: cc::Build::try_compile::{{closure}}
             at /Users/matthieu/.cargo/registry/src/github.com-1ecc6299db9ec823/cc-1.0.25/src/lib.rs:933
   9: build_script_build::main
             at ./build.rs:93
  10: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:105
  13: <std::sync::mutex::Mutex<T>>::new
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  15: build_script_build::main
```

**Comment by alexcrichton** [comment]
You could try executing those commands manually perhaps, but unfortunately I'm not sure what's going on. It doesn't look related to this crate though and moreso related to your toolchain

**Comment by zandeck** [comment]
All the files seem to be generate and it keeps failing on this command it seems

```
192:hello matthieu$ ar crs -v /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/libbacktrace.a /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/alloc.o /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/dwarf.o /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/fileline.o /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/posix.o /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/read.o /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/sort.o /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/state.o /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/macho.o
r - /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/alloc.o
r - /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/dwarf.o
r - /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/fileline.o
r - /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/posix.o
r - /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/read.o
r - /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/sort.o
r - /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/state.o
r - /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/src/libbacktrace/macho.o
/opt/local/bin/ranlib: object: /Users/matthieu/Documents/Rust/actix/hello/target/debug/build/backtrace-sys-d535610cdc639293/out/libbacktrace.a(alloc.o) malformed object (unknown load command 1)
ar: internal ranlib command failed
```

Do you know if there is any way to get more log when it runs?

I see that this library uses objcopy aside of ar and make. Is it this name that is used on macOS as well? (-bash: objcopy: command not found on my system) Are these 3 libraries supposed to be already included in macOS?

**Comment by zandeck** [comment]
It changed because I remove cctools that I installed through Brew and see if things were working better. Unfortunately, it didn't change much it seems. Still investigating.

**Comment by zandeck** [comment]
Quick update: it seems to work now.
I had to install MacPorts and install cctools through it.
For some reason, installing it through brew didn't work.

**Comment by adamnemecek** [comment]
It seems like cctools has been removed from brew. What now?
