### ISSUE TITLE
Broken on latest nightly

### ISSUE THREAD

**Issue by SergioBenitez** [alexcrichton/backtrace-rs#24]
On Linux using the latest nightly (`01-31-2017`), the library fails due to undefined references. `cargo test` results in:

```
$ cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running target/debug/deps/backtrace-8f69c3ae17590833

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured

     Running target/debug/deps/smoke-b4bc19c251bc60fa

running 2 tests
test smoke_test_frames ... ok
test many_threads ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured

   Doc-tests backtrace

running 4 tests
test backtrace::trace_0 ... ok
test symbolize::resolve_0 ... FAILED
test _0 ... FAILED
test capture::Backtrace::new_0 ... FAILED

failures:

---- symbolize::resolve_0 stdout ----
	warning: unused variable: `symbol`, #[warn(unused_variables)] on by default
 --> <anon>:7:33
  |
7 |         backtrace::resolve(ip, |symbol| {
  |                                 ^^^^^^

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/rustdoctest.BKeX4H9JaL0D/rust_out.0.o" "-o" "/tmp/rustdoctest.BKeX4H9JaL0D/rust_out" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/tmp/backtrace-rs/target/debug/deps" "-L" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/tmp/backtrace-rs/target/debug/deps/libbacktrace-e72a309f309020de.rlib" "/tmp/backtrace-rs/target/debug/deps/librustc_demangle-ffe0cd46130fc1c4.rlib" "/tmp/backtrace-rs/target/debug/deps/libbacktrace_sys-efea7818ed02b81a.rlib" "/tmp/backtrace-rs/target/debug/deps/liblibc-2a4507ee5e52ea3e.rlib" "/tmp/backtrace-rs/target/debug/deps/libcfg_if-5cf5b4dd25466da1.rlib" "-L" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "std-93390f7535a2b2f7" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-5d4fca8590bb0079.rlib" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /tmp/backtrace-rs/target/debug/deps/libbacktrace-e72a309f309020de.rlib(backtrace-e72a309f309020de.0.o): In function `backtrace::symbolize::libbacktrace::init_state::{{closure}}':
          /tmp/backtrace-rs/src/symbolize/mod.rs:159: undefined reference to `backtrace_create_state'
          /tmp/backtrace-rs/target/debug/deps/libbacktrace-e72a309f309020de.rlib(backtrace-e72a309f309020de.0.o): In function `backtrace::symbolize::libbacktrace::resolve':
          /tmp/backtrace-rs/src/symbolize/mod.rs:159: undefined reference to `backtrace_pcinfo'
          /tmp/backtrace-rs/src/symbolize/mod.rs:159: undefined reference to `backtrace_syminfo'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:453
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'rustc' panicked at 'couldn't compile the test', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustdoc/test.rs:265

---- _0 stdout ----
	warning: unused variable: `symbol_address`, #[warn(unused_variables)] on by default
 --> <anon>:6:13
  |
6 |         let symbol_address = frame.symbol_address();
  |             ^^^^^^^^^^^^^^

warning: unused variable: `name`, #[warn(unused_variables)] on by default
  --> <anon>:10:25
   |
10 |             if let Some(name) = symbol.name() {
   |                         ^^^^

warning: unused variable: `filename`, #[warn(unused_variables)] on by default
  --> <anon>:13:25
   |
13 |             if let Some(filename) = symbol.filename() {
   |                         ^^^^^^^^

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/rustdoctest.I0qW5cADJTz7/rust_out.0.o" "-o" "/tmp/rustdoctest.I0qW5cADJTz7/rust_out" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/tmp/backtrace-rs/target/debug/deps" "-L" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/tmp/backtrace-rs/target/debug/deps/libbacktrace-e72a309f309020de.rlib" "/tmp/backtrace-rs/target/debug/deps/librustc_demangle-ffe0cd46130fc1c4.rlib" "/tmp/backtrace-rs/target/debug/deps/libbacktrace_sys-efea7818ed02b81a.rlib" "/tmp/backtrace-rs/target/debug/deps/liblibc-2a4507ee5e52ea3e.rlib" "/tmp/backtrace-rs/target/debug/deps/libcfg_if-5cf5b4dd25466da1.rlib" "-L" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "std-93390f7535a2b2f7" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-5d4fca8590bb0079.rlib" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /tmp/backtrace-rs/target/debug/deps/libbacktrace-e72a309f309020de.rlib(backtrace-e72a309f309020de.0.o): In function `backtrace::symbolize::libbacktrace::init_state::{{closure}}':
          /tmp/backtrace-rs/src/symbolize/mod.rs:159: undefined reference to `backtrace_create_state'
          /tmp/backtrace-rs/target/debug/deps/libbacktrace-e72a309f309020de.rlib(backtrace-e72a309f309020de.0.o): In function `backtrace::symbolize::libbacktrace::resolve':
          /tmp/backtrace-rs/src/symbolize/mod.rs:159: undefined reference to `backtrace_pcinfo'
          /tmp/backtrace-rs/src/symbolize/mod.rs:159: undefined reference to `backtrace_syminfo'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:453
thread 'rustc' panicked at 'couldn't compile the test', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustdoc/test.rs:265

---- capture::Backtrace::new_0 stdout ----
	warning: unused variable: `current_backtrace`, #[warn(unused_variables)] on by default
 --> <anon>:5:5
  |
5 | let current_backtrace = Backtrace::new();
  |     ^^^^^^^^^^^^^^^^^

error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/rustdoctest.drtYPrbUoAPN/rust_out.0.o" "-o" "/tmp/rustdoctest.drtYPrbUoAPN/rust_out" "-Wl,--gc-sections" "-pie" "-nodefaultlibs" "-L" "/tmp/backtrace-rs/target/debug/deps" "-L" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "-Wl,-Bdynamic" "/tmp/backtrace-rs/target/debug/deps/libbacktrace-e72a309f309020de.rlib" "/tmp/backtrace-rs/target/debug/deps/librustc_demangle-ffe0cd46130fc1c4.rlib" "/tmp/backtrace-rs/target/debug/deps/libbacktrace_sys-efea7818ed02b81a.rlib" "/tmp/backtrace-rs/target/debug/deps/liblibc-2a4507ee5e52ea3e.rlib" "/tmp/backtrace-rs/target/debug/deps/libcfg_if-5cf5b4dd25466da1.rlib" "-L" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-l" "std-93390f7535a2b2f7" "/home/u1/sbenitez/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-5d4fca8590bb0079.rlib" "-l" "util" "-l" "dl" "-l" "rt" "-l" "pthread" "-l" "gcc_s" "-l" "pthread" "-l" "c" "-l" "m" "-l" "rt" "-l" "util"
  = note: /tmp/backtrace-rs/target/debug/deps/libbacktrace-e72a309f309020de.rlib(backtrace-e72a309f309020de.0.o): In function `backtrace::symbolize::libbacktrace::init_state::{{closure}}':
          /tmp/backtrace-rs/src/symbolize/mod.rs:159: undefined reference to `backtrace_create_state'
          /tmp/backtrace-rs/target/debug/deps/libbacktrace-e72a309f309020de.rlib(backtrace-e72a309f309020de.0.o): In function `backtrace::symbolize::libbacktrace::resolve':
          /tmp/backtrace-rs/src/symbolize/mod.rs:159: undefined reference to `backtrace_pcinfo'
          /tmp/backtrace-rs/src/symbolize/mod.rs:159: undefined reference to `backtrace_syminfo'
          collect2: error: ld returned 1 exit status


error: aborting due to previous error

thread 'rustc' panicked at 'Box<Any>', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustc_errors/lib.rs:453
thread 'rustc' panicked at 'couldn't compile the test', /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/librustdoc/test.rs:265


failures:
    _0
    capture::Backtrace::new_0
    symbolize::resolve_0

test result: FAILED. 1 passed; 3 failed; 0 ignored; 0 measured

error: test failed
```

**Comment by alexcrichton** [comment]
Fixed in https://github.com/alexcrichton/backtrace-rs/commit/390ea2a3b630d5bcb83b02c8c6ce814b9d5df7d8, thanks for the report!
