### ISSUE TITLE
Cross compiling backtrace-sys 0.1.6

### ISSUE THREAD

**Issue by tl8roy** [alexcrichton/backtrace-rs#25]
I did a cargo update on my project and that bumped up the version of backtrace-sys to 0.1.6.

Unfortunately, this has resulted in the build of the project failing. It does build on Windows but not when cross compiling for ARM Linux.

This is the error message that I got:

```
error: failed to run custom build command for `backtrace-sys v0.1.6`
process didn't exit successfully: `/home/tlostroh/project/target/release/build/backtrace-sys-630598d76a7afd9a/build-script-build` (exit code: 101)
--- stdout
OPT_LEVEL = Some("3")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("i686-unknown-linux-gnu")
TARGET = Some("armv7-unknown-linux-gnueabihf")
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("i686-unknown-linux-gnu")
CC_armv7-unknown-linux-gnueabihf = None
CC_armv7_unknown_linux_gnueabihf = None
TARGET_CC = None
CC = None
HOST = Some("i686-unknown-linux-gnu")
CROSS_COMPILE = None
TARGET = Some("armv7-unknown-linux-gnueabihf")
HOST = Some("i686-unknown-linux-gnu")
CFLAGS_armv7-unknown-linux-gnueabihf = None
CFLAGS_armv7_unknown_linux_gnueabihf = None
TARGET_CFLAGS = None
CFLAGS = None
PROFILE = Some("release")
running: "/home/tlostroh/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/src/libbacktrace/configure" "--with-pic" "--disable-multilib" "--disable-shared" "--disable-host-shared" "--target=armv7-unknown-linux-gnueabihf" "--host=i686-unknown-linux-gnu"
checking build system type... i686-pc-linux-gnu
checking host system type... i686-unknown-linux-gnu
checking target system type... armv7-unknown-linux-gnueabihf
checking for i686-unknown-linux-gnu-gcc... arm-linux-gnueabihf-gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... yes
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether arm-linux-gnueabihf-gcc accepts -g... yes
checking for arm-linux-gnueabihf-gcc option to accept ISO C89... none needed
checking how to run the C preprocessor... arm-linux-gnueabihf-gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking minix/config.h usability... no
checking minix/config.h presence... no
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for i686-unknown-linux-gnu-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for i686-unknown-linux-gnu-gcc... (cached) arm-linux-gnueabihf-gcc
checking whether we are using the GNU C compiler... (cached) yes
checking whether arm-linux-gnueabihf-gcc accepts -g... (cached) yes
checking for arm-linux-gnueabihf-gcc option to accept ISO C89... (cached) none needed
checking for i686-unknown-linux-gnu-ranlib... no
checking for ranlib... ranlib
checking for gawk... (cached) mawk
checking how to print strings... printf
checking for a sed that does not truncate output... /bin/sed
checking for fgrep... /bin/grep -F
checking for ld used by arm-linux-gnueabihf-gcc... /usr/arm-linux-gnueabihf/bin/ld
checking if the linker (/usr/arm-linux-gnueabihf/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... no
checking for i686-unknown-linux-gnu-dumpbin... no
checking for i686-unknown-linux-gnu-link... no
checking for dumpbin... no
checking for link... link -dump
checking the name lister (nm) interface... BSD nm
checking whether ln -s works... no, using cp -p
checking the maximum length of command line arguments... 1572864
checking whether the shell understands some XSI constructs... yes
checking whether the shell understands "+="... yes
checking for /usr/arm-linux-gnueabihf/bin/ld option to reload object files... -r
checking for i686-unknown-linux-gnu-objdump... no
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for i686-unknown-linux-gnu-ar... no
checking for ar... ar
checking for i686-unknown-linux-gnu-strip... strip
checking for i686-unknown-linux-gnu-ranlib... ranlib
checking command to parse nm output from arm-linux-gnueabihf-gcc object... ok
checking for dlfcn.h... yes
checking for objdir... .libs
checking if arm-linux-gnueabihf-gcc supports -fno-rtti -fno-exceptions... no
checking for arm-linux-gnueabihf-gcc option to produce PIC... -fPIC -DPIC
checking if arm-linux-gnueabihf-gcc PIC flag -fPIC -DPIC works... yes
checking if arm-linux-gnueabihf-gcc static flag -static works... yes
checking if arm-linux-gnueabihf-gcc supports -c -o file.o... yes
checking if arm-linux-gnueabihf-gcc supports -c -o file.o... (cached) yes
checking whether the arm-linux-gnueabihf-gcc linker (/usr/arm-linux-gnueabihf/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking unwind.h usability... yes
checking unwind.h presence... yes
checking for unwind.h... yes
checking for _Unwind_Backtrace... yes
checking for -funwind-tables option... yes
checking for -frandom-seed=string option... yes
checking whether arm-linux-gnueabihf-gcc supports -W... yes
checking whether arm-linux-gnueabihf-gcc supports -Wall... yes
checking whether arm-linux-gnueabihf-gcc supports -Wwrite-strings... yes
checking whether arm-linux-gnueabihf-gcc supports -Wstrict-prototypes... yes
checking whether arm-linux-gnueabihf-gcc supports -Wmissing-prototypes... yes
checking whether arm-linux-gnueabihf-gcc supports -Wold-style-definition... yes
checking whether arm-linux-gnueabihf-gcc supports -Wmissing-format-attribute... yes
checking whether arm-linux-gnueabihf-gcc supports -Wcast-qual... yes
checking for _Unwind_GetIPInfo... yes
checking __sync extensions... yes
checking __atomic extensions... yes
checking output filetype... elf32
looking for a compliant stdint.h in stdint.h, checking for uintmax_t... yes
checking for uintptr_t... yes
checking for int_least32_t... yes
checking for int_fast32_t... yes
checking for uint64_t... yes
checking what to include in gstdint.h... stdint.h (already complete)
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking for mmap... yes
checking link.h usability... yes
checking link.h presence... yes
checking for link.h... yes
checking for dl_iterate_phdr... yes
checking for fcntl... yes
checking whether strnlen is declared... yes
checking for getexecname... no
checking whether tests can run... no
configure: creating ./config.status
config.status: creating Makefile
config.status: creating backtrace-supported.h
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing libtool commands
config.status: executing gstdint.h commands
config.status: executing default commands
running: "make" "INCDIR=/home/tlostroh/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/src/libbacktrace"
make  all-am
make[1]: Entering directory '/home/tlostroh/project/target/armv7-unknown-linux-gnueabihf/release/build/backtrace-sys-b2e53518d4e6e892/out'
/bin/bash ./libtool --tag=CC   --mode=compile arm-linux-gnueabihf-gcc -DHAVE_CONFIG_H -I. -I/home/tlostroh/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/src/libbacktrace  -I /home/tlostroh/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/src/libbacktrace/../include -I /home/tlostroh/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/src/libbacktrace/../libgcc -I ../libgcc  -funwind-tables -frandom-seed=state.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -fPIC -O3 -ffunction-sections -fdata-sections -fPIC -march=armv7-a -c -o state.lo /home/tlostroh/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/src/libbacktrace/state.c
libtool: compile:  arm-linux-gnueabihf-gcc -DHAVE_CONFIG_H -I. -I/home/tlostroh/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/src/libbacktrace -I /home/tlostroh/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/src/libbacktrace/../include -I /home/tlostroh/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/src/libbacktrace/../libgcc -I ../libgcc -funwind-tables -frandom-seed=state.lo -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -fPIC -O3 -ffunction-sections -fdata-sections -fPIC -march=armv7-a -c /home/tlostroh/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/src/libbacktrace/state.c  -fPIC -DPIC -o state.o
/bin/bash ./libtool --tag=CC   --mode=link arm-linux-gnueabihf-gcc -funwind-tables -frandom-seed=libbacktrace.la -W -Wall -Wwrite-strings -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -Wmissing-format-attribute -Wcast-qual -fPIC -O3 -ffunction-sections -fdata-sections -fPIC -march=armv7-a   -o libbacktrace.la  atomic.lo dwarf.lo fileline.lo posix.lo print.lo sort.lo state.lo backtrace.lo simple.lo elf.lo mmapio.lo mmap.lo 
libtool: link: rm -fr  .libs/libbacktrace.la
libtool: link: ar cru .libs/libbacktrace.a  atomic.o dwarf.o fileline.o posix.o print.o sort.o state.o backtrace.o simple.o elf.o mmapio.o mmap.o
libtool: link: ranlib .libs/libbacktrace.a
libtool: link: ( cd ".libs" && rm -f "libbacktrace.la" && cp -p "../libbacktrace.la" "libbacktrace.la" )
true  DO=all multi-do # make
make[1]: Leaving directory '/home/tlostroh/project/target/armv7-unknown-linux-gnueabihf/release/build/backtrace-sys-b2e53518d4e6e892/out'
cargo:rustc-link-search=native=/home/tlostroh/project/target/armv7-unknown-linux-gnueabihf/release/build/backtrace-sys-b2e53518d4e6e892/out/.libs
cargo:rustc-link-lib=static=backtrace
running: "ar" "x" "/home/tlostroh/project/target/armv7-unknown-linux-gnueabihf/release/build/backtrace-sys-b2e53518d4e6e892/out/.libs/libbacktrace.a"
running: "objcopy" "--redefine-syms=symbol-map" "/home/tlostroh/project/target/armv7-unknown-linux-gnueabihf/release/build/backtrace-sys-b2e53518d4e6e892/out/__tmp/atomic.o"

--- stderr
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
configure: WARNING: using cross tools not prefixed with host triplet
ar: `u' modifier ignored since `D' is the default (see `U')
objcopy: Unable to recognise the format of the input file `/home/tlostroh/project/target/armv7-unknown-linux-gnueabihf/release/build/backtrace-sys-b2e53518d4e6e892/out/__tmp/atomic.o'
thread 'main' panicked at 'failed with: exit code: 1', /home/tlostroh/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/build.rs:94
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

If I downgrade the version to 0.1.5 in the ```Cargo.lock``` file, everything works as expected.

**Comment by zzeroo** [comment]
I ran into the same issue.

```bash
| arm-poky-linux-gnueabi-ar: `u' modifier ignored since `D' is the default (see `U')
| objcopy: Unable to recognise the format of the input file `/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r2/target/armv7
-unknown-linux-gnueabihf/release/build/backtrace-sys-c5e6113905bd3f96/out/__tmp/atomic.o'
| thread 'main' panicked at 'failed with: exit code: 1', /mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r2/cargo_home/regis
try/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.6/build.rs:94
| stack backtrace:
|    1:     0x55a5cc3c8aac - std::sys::imp::backtrace::tracing::imp::write::h1d59ca58eb86a1e2
|                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
|    2:     0x55a5cc3ced5e - std::panicking::default_hook::{{closure}}::hc8550e2dc230bf9b
|                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
|    3:     0x55a5cc3ce964 - std::panicking::default_hook::he85ae9e5c9867198
|                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
|    4:     0x55a5cc3cf13b - std::panicking::rust_panic_with_hook::h319375f6b98710b0
|                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
|    5:     0x55a5cc3cefd4 - std::panicking::begin_panic::hbfd2ece4b73bdca6
|                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
|    6:     0x55a5cc3ceef9 - std::panicking::begin_panic_fmt::h8409f0145843dd1f
|                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
|    7:     0x55a5cc3b5ebe - build_script_build::run::h38783002fa4ae0be
|    8:     0x55a5cc3b4f0a - build_script_build::main::hc9806a7718b1ded5
|    9:     0x55a5cc3d7ada - __rust_maybe_catch_panic
|                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
|   10:     0x55a5cc3cf8a6 - std::rt::lang_start::h0637c2e100ff36fc
|                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
|                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
|                         at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
|   11:     0x7f3e7dcc72b0 - __libc_start_main
|   12:     0x55a5cc3b2c19 - _start
|   13:                0x0 - <unknown>
|
```

@tl8roy Thank you for the hint with the Cargo.lock, downgrade solution, It works for me, too.

**Comment by alexcrichton** [comment]
Ah yeah this is due to the recent update to use `objcopy`, and it looks like not all `objcopy` binaries are created equal! I'll implement a fix that infers the name of the binary from the compiler being used, and that should suffice for most cases I think.

**Comment by alexcrichton** [comment]
@tl8roy and @zzeroo I think I've fixed this on master with https://github.com/alexcrichton/backtrace-rs/commit/1e4d485791efec39e410c639adc9146df5a9b15b, can you test that out and see if it works for you?

**Comment by golddranks** [comment]
I'm experiencing the same issue. (Building on Musl.) Gonna check the master branch real soon.

**Comment by golddranks** [comment]
So, I'm building with a musl target, and the build broke recently. I tested to build backtrace-sys with the newest master, and get this:

    failed to execute command: No such file or directory (os error 2)
    Is `musl-objcopy` not installed?

Curiously, when I tried with the 0.1.6 commit ( 456848c46a7abf856135ccf270b19d27742641c7 ), it builds, which confuses the hell out of me. Why does it build now, but originally broke when I started to investigate it.

**Comment by ssokolow** [comment]
I'm experiencing a similar "0.1.6 broke musl builds" situation (specifically, targeting `i686-unknown-linux-musl` from `x86_64-unknown-linux-gnu`) but, in my case, looking at `config.log` says that it's dying because `musl-gcc: command not found`.

...and that hasn't changed. I clearly remember:

1. It was working
2. `rustup update`
3. Still working
4. `cargo update`
5. Broken.

(No meddling with `apt-get` in the interim)

**Comment by alexcrichton** [comment]
Ok I think I just pushed up a fix for musl. Can you provide the full logs for failure with arm though?

**Comment by ssokolow** [comment]
I'll try to make time to figure out how to substitute git master later today and let you know how it goes.

I'm still on 0.1.6 because I've never had to build from something not yet on crates.io before. My intent in mentioning the problems was twofold:

1. Point out that backtrace-rs 0.1.6 is the only crate I've found which expects to find musl tooling rather than just the `rust-std` that rustup installs for it.

2. Verify that the ARM breakage in 0.1.6 wasn't limited to `armv7-unknown-linux-gnueabihf`

(It's not personally urgent anymore because I realized that I could opt out of `error-chain`'s backtrace-rs dependency... something I should be doing anyway, given that I'm already building with `panic="abort"` in my release builds to help dead code elimination reduce the binary size.)

**Comment by golddranks** [comment]
Tested the newest commit, works for me.

**Comment by alexcrichton** [comment]
Ok, published a new version!

**Comment by ssokolow** [comment]
Sorry for the wait. (It's still technically "today" by my sleep cycle)

backtrace-sys 0.1.7 still blows up with `musl-gcc: command not found` in `config.log` here while the rest of my crates cross-build just fine.

**Comment by alexcrichton** [comment]
@ssokolow I think `musl-gcc` is required when compiling for musl?

**Comment by ssokolow** [comment]
Nope. It used to work for backtrace and it still works for every other crate I've depended on so far.

While there may be other `-sys` crates which depend on `musl-gcc` that I've yet to encounter, backtrace 0.1.6+ is the only one so far which isn't satisfied with `rustup target add i686-unknown-linux-musl`.

(Now, I'm just trying to decide whether to leave `default-features = false` in my `error-chain` config or look for a way to pin `backtrace-rs` at 0.1.5 in the dependency resolver.)

**Comment by alexcrichton** [comment]
@ssokolow can you gist the full logs of what you're doing locally? It may be the case that no other crate requires compiling native code (like backtrace-sys does) in which case typically `musl-gcc` isn't required but it is for backtrace-sys itself.

**Comment by ssokolow** [comment]
I'm not sure which logs you specifically want, given that I'm not overly experienced with the internals of the rust build process. (The only reason I knew to check `config.log` is because the error message said so and I know how to use the `find` command.)

I'd rather not blindly try to post every log-like thing I can find (lots of effort that may be wasted), but, to answer the question you seem to be asking, here's a visualization of the dependency tree in the "opted out of backtrace so it builds successfully" configuration:

```
ssokolow@monolith rip_media [master] % cargo tree
rip_media v0.1.0 (file:///home/ssokolow/src/rip_media)
├── clap v2.20.3
│   ├── ansi_term v0.9.0
│   ├── bitflags v0.7.0
│   ├── libc v0.2.20
│   ├── strsim v0.6.0
│   ├── term_size v0.2.2
│   │   └── libc v0.2.20 (*)
│   ├── unicode-segmentation v1.1.0
│   ├── unicode-width v0.1.4
│   └── vec_map v0.6.0
├── error-chain v0.9.0
├── glob v0.2.11
├── libc v0.2.20 (*)
└── rustyline v1.0.0
    ├── encode_unicode v0.1.3
    ├── libc v0.2.20 (*)
    ├── nix v0.5.1
    │   ├── bitflags v0.4.0
    │   └── libc v0.2.20 (*)
    └── unicode-width v0.1.4 (*)
```

Given that I'm actively using the `libc` crate to call `access(2)` via an `unsafe` block, I'm assuming that, by "requires compiling native code", you mean actual `.c` files, rather than simply binding to a pre-existing library.

**Comment by tl8roy** [comment]
So I can confirm that the original issue has been resolved when cross compiling.

**Comment by zzeroo** [comment]
@alexcrichton version 0.1.7 from crates.io does not work for me. Same error I think. Maybe there are errors in our cross build environment. Later this day I try to compile your git master branch on real hardware.

```bash
NOTE: which rustc: /home/smueller/.cargo/bin/rustc
NOTE: rustc --version rustc 1.17.0-nightly (c49d10207 2017-02-07)
NOTE: which cargo: /home/smueller/.cargo/bin/cargo
NOTE: cargo --version cargo-0.18.0-nightly (de2919f 2017-02-06)
NOTE: cargo build --verbose --manifest-path /mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/git/Cargo.toml --target=armv7-unknown-linux-gnueabihf --release
...
configure: WARNING: If you wanted to set the --build type, don't use --host.
    If a cross compiler is detected then cross compile mode will be used.
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/atomic.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* atomic.c -- Support for atomic functions if not present.
 
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/dwarf.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* dwarf.c -- Get file/line information from DWARF for backtraces.
 
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/fileline.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* fileline.c -- Get file and line number information in a backtrace.
 
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/posix.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* posix.c -- POSIX file I/O routines for the backtrace library.
 
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/print.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* print.c -- Print the current backtrace.
 
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/sort.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* sort.c -- Sort without allocating memory
 
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/state.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* state.c -- Create the backtrace state.
 
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/backtrace.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* backtrace.c -- Entry point for stack backtrace library.
 
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/simple.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* simple.c -- The backtrace_simple function.
 
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/elf.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* elf.c -- Get debug data from an ELF file for backtraces.
 
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/mmapio.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* mmapio.c -- File views using mmap.
 
/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/src/libbacktrace/mmap.c:1:0: warning: switch -mcpu=cortex-a7 conflicts with -march=armv7-a switch
 /* mmap.c -- Memory allocation with mmap.
 
arm-poky-linux-gnueabi-ar: `u' modifier ignored since `D' is the default (see `U')
objcopy: Unable to recognise the format of the input file `/mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/target/armv7-unknown-linux-gnueabihf/release/build/backtrace-sys-841723acfede06fc/out/__tmp/atomic.o'
thread 'main' panicked at 'failed with: exit code: 1', /mnt/src/poky/build/tmp/work/cortexa7hf-neon-vfpv4-poky-linux-gnueabi/xmz-mod-touch-server/0.21.4-r8/cargo_home/registry/src/github.com-1ecc6299db9ec823/backtrace-sys-0.1.7/build.rs:116
stack backtrace:
   1:     0x561ae818d1cc - std::sys::imp::backtrace::tracing::imp::write::h1d59ca58eb86a1e2
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
   2:     0x561ae819347e - std::panicking::default_hook::{{closure}}::hc8550e2dc230bf9b
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:351
   3:     0x561ae8193084 - std::panicking::default_hook::he85ae9e5c9867198
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:367
   4:     0x561ae819385b - std::panicking::rust_panic_with_hook::h319375f6b98710b0
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:555
   5:     0x561ae81936f4 - std::panicking::begin_panic::hbfd2ece4b73bdca6
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:517
   6:     0x561ae8193619 - std::panicking::begin_panic_fmt::h8409f0145843dd1f
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:501
   7:     0x561ae817a3fd - build_script_build::run::he56952b16e6aa376
   8:     0x561ae817810c - build_script_build::main::h7e277504e1a88bc9
   9:     0x561ae819c1fa - __rust_maybe_catch_panic
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libpanic_unwind/lib.rs:98
  10:     0x561ae8193fc6 - std::rt::lang_start::h0637c2e100ff36fc
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panicking.rs:436
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/panic.rs:361
                        at /buildslave/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libstd/rt.rs:57
  11:     0x7fc18ab792b0 - __libc_start_main
  12:     0x561ae8175c79 - _start
  13:                0x0 - <unknown>

Build failed, waiting for other jobs to finish...
error: build failed
WARNING: exit code 101 from a shell command.
```

**Comment by alexcrichton** [comment]
@ssokolow yeah none of those other crates require compiling C code, and this crate requires that, which is why you'll need to install musl-gcc

@zzeroo do you have an `arm-poky-linux-gnueabi-objcopy` binary on the system?

**Comment by ssokolow** [comment]
Huh. Is that a new requirement? I could be wrong, but I seem to remember making successful cross-builds during the period when my `Cargo.lock` was listing `backtrace-sys 0.1.5`.

**Comment by zzeroo** [comment]
@alexcrichton I looks like `arm-poky-linux-gnueabi-objcopy` is there. But none of the versions since 0.1.5 can get cross compiled.

And for the record. I use a build system based on open-embedded/ yocto without musl stuff here.

```bash
# file ../rootfs/usr/bin/arm-poky-linux-gnueabi-objcopy
../rootfs/usr/bin/arm-poky-linux-gnueabi-objcopy: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=31b324a3a3f715e03bf526fd12a85561a669cbf0, stripped
```

```bash
# file ../rootfs/usr/bin/arm-poky-linux-gnueabi-objcopy
../rootfs/usr/bin/arm-poky-linux-gnueabi-objcopy: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=31b324a3a3f715e03bf526fd12a85561a669cbf0, stripped
```

**Comment by zzeroo** [comment]
Here is a complete log: https://gist.github.com/zzeroo/c8fdc52f5c8d289b53c3eb1c3d778077

**Comment by alexcrichton** [comment]
@ssokolow yes in backtrace-sys-0.1.15 no C code was compiled on Linux, now in backtrace-sys-0.1.16+ C code needs to be compiled.

@zzeroo the error is that `objcopy` is run, not `arm-poky-linux-gnueabi-objcopy`, which means that [this is failing to find the latter](https://github.com/alexcrichton/backtrace-rs/blob/master/backtrace-sys/build.rs#L92-L102). Is that file in your `PATH`?

**Comment by ssokolow** [comment]
Ahh. In that case, I'll have to see whether @brson would be willing to provide any kind of guaranteed support for having the `backtrace` feature pinned to 0.1.5.

Complicating the build with C code is an unacceptable regression in my eyes, but it'd be nice if I didn't have to take the nuclear option and rely on `default-features = false`.
