### ISSUE TITLE
Error building since sys 0.1.6

### ISSUE THREAD

**Issue by dten** [alexcrichton/backtrace-rs#33]
Using a crate that uses backtrace and `cargo update` got me from backtrace-sys 0.1.5 to a more recent one and since then i get this error. going back to 0.1.5 fixes it (and backtraces work)

```
--- stdout
OPT_LEVEL = Some("1")
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-pc-windows-msvc")
TARGET = Some("aarch64-linux-android")
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-pc-windows-msvc")
CC_aarch64-linux-android = None
CC_aarch64_linux_android = None
TARGET_CC = Some("C:\\Users\\David\\Documents\\Android\\ndk\\android-ndk-r13b\\toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64\\bin/aarch64-linux-android-gcc")
TARGET = Some("aarch64-linux-android")
HOST = Some("x86_64-pc-windows-msvc")
CFLAGS_aarch64-linux-android = None
CFLAGS_aarch64_linux_android = None
TARGET_CFLAGS = Some("--sysroot C:\\Users\\David\\Documents\\Android\\ndk\\android-ndk-r13b\\platforms/android-24/arch-arm64")
PROFILE = Some("debug")
running: "C:\\Users\\David\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\backtrace-sys-0.1.6\\src/libbacktrace/configure" "--with-pic" "--disable-multilib" "--disable-shared" "--disable-host-shared" "--target=aarch64-linux-android" "--host=x86_64-pc-windows-msvc"

--- stderr
thread 'main' panicked at 'failed to get status: %1 is not a valid Win32 application. (os error 193)', C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-sys-0.1.6\build.rs:91
stack backtrace:
   0:     0x7ff79f8b5fc8 - std::panicking::default_hook::{{closure}}
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:356
   1:     0x7ff79f8b54d4 - std::panicking::default_hook
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:367
   2:     0x7ff79f8b8dad - std::panicking::rust_panic_with_hook
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:555
   3:     0x7ff79f8b8bf8 - std::panicking::begin_panic<collections::string::String>
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:517
   4:     0x7ff79f8b8b64 - std::panicking::begin_panic_fmt
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\panicking.rs:501
   5:     0x7ff79f8834a8 - build_script_build::run
                        at C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-sys-0.1.6\build.rs:91
   6:     0x7ff79f881fc9 - build_script_build::main
                        at C:\Users\David\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-sys-0.1.6\build.rs:46
   7:     0x7ff79f8bb301 - panic_unwind::__rust_maybe_catch_panic
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libpanic_unwind\lib.rs:98
   8:     0x7ff79f8b939a - std::rt::lang_start
                        at C:\bot\slave\nightly-dist-rustc-win-msvc-64\build\src\libstd\rt.rs:51
   9:     0x7ff79f8bfb58 - __scrt_common_main_seh
                        at f:\dd\vctools\crt\vcstartup\src\startup\exe_common.inl:253
  10:     0x7ffb1dc88363 - BaseThreadInitThunk

Error executing ["cargo", "rustc", "--target", "aarch64-linux-android", "--", "-C", "linker=C:\\d\\Documents\\Repositories\\TeamRocket\\gameboyemulator\\gameboy\\target\\android-artifacts\\linker_exe.exe", "--extern", "cargo_apk_injected_glue=C:\\d\\Documents\\Repositories\\TeamRocket\\gameboyemulator\\gameboy\\target\\android-artifacts\\aarch64-linux-android\\libcargo_apk_injected_glue.rlib"]
Status code 101
```

**Comment by alexcrichton** [comment]
Thanks for the report! Could you try the master branch and see if it fixes these issues?
